# Generated by Django 5.1.7 on 2025-04-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_artikel_bild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestellteartikel',
            old_name='Bestellung',
            new_name='bestellung',
        ),
        migrations.AlterField(
            model_name='artikel',
            name='preis',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
