# Generated by Django 5.1.7 on 2025-04-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_bestellung_bestellteartikel_bestellung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='preis',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
